language: php
php:
  - 5.5
before_script:
  - mysql -e 'create database Lenticularis;'
  - mysql -u root -p  Lenticularis < ./Dump.sql
script: phpunit --configuration ./runTests.xml
# whitelist
branches:
  only:
    - Lenticularis
