language: php
php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_script:
  - mysql -e 'create database Lenticularis;'
  - mysql -u root  Lenticularis < ./Dumps/TestDump.sql
  - chmod 777 ./Storage
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install
script: phpunit --configuration ./runTests.xml
# whitelist
branches:
  only:
    - Lenticularis
after_success:
  - bash <(curl -s https://codecov.io/bash)
