language: php
php:
  - 5.5
before_script:
  - mysql -e 'create database Lenticularis;'
  - mysql -u root  Lenticularis < ./Dumps/TestDump.sql
  - chmod 777 ./Storage
script: phpunit --configuration ./runTests.xml
# whitelist
branches:
  only:
    - Lenticularis
after_success:
  - bash <(curl -s https://codecov.io/bash)
